async function api(url,opt={}){const r=await fetch(url,{credentials:"same-origin",...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||"Request failed");return d}
const $=s=>document.querySelector(s),msg=(t,type="error")=>{const e=$("[data-message]");e.hidden=false;e.textContent=t;e.className="form-message "+type};
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
let courses=[],selected="";
async function loadCourses(){const d=await api("/api/courses?admin=true");courses=d.courses;const s=$("[data-course-select]");s.innerHTML=courses.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.title)+'</option>').join("");selected=s.value;await loadContent()}
async function loadContent(){if(!selected)return;const d=await api("/api/course-content?courseId="+encodeURIComponent(selected)+"&admin=true"),phase=$("[data-phase-select]");phase.innerHTML=d.phases.length?d.phases.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.order)+'. '+esc(p.title)+'</option>').join(""):'<option value="">Create a phase first</option>';const list=$("[data-content-list]");if(!d.phases.length){list.innerHTML="<div class=\"my-courses-empty\"><h2>No phases yet</h2><p>Add the first phase above.</p></div>";return}list.innerHTML=d.phases.map(p=>'<article class="course-card content-row"><div><p class="eyebrow">PHASE '+esc(p.order)+' · '+esc(p.status)+'</p><h3>'+esc(p.title)+'</h3><p>'+esc(p.description)+'</p></div><button class="btn btn-small" data-phase-publish="'+esc(p.id)+'">'+(p.status==="published"?"Unpublish":"Publish")+'</button><div class="lesson-stack">'+d.lessons.filter(l=>l.phaseId===p.id).map(l=>'<div class="lesson-admin-item"><div><b>'+esc(l.order)+'. '+esc(l.title)+'</b><span>'+esc(l.status)+(l.duration?" · "+esc(l.duration):"")+'</span></div><button class="btn btn-small" data-lesson-publish="'+esc(l.id)+'">'+(l.status==="published"?"Unpublish":"Publish")+'</button></div>').join("")+'</div></article>').join("");bindActions()}
function bindActions(){document.querySelectorAll("[data-phase-publish]").forEach(b=>b.onclick=async()=>{const d=await api("/api/course-content?courseId="+encodeURIComponent(selected)+"&admin=true");const p=d.phases.find(x=>x.id===b.dataset.phasePublish);await api("/api/course-content?courseId="+encodeURIComponent(selected)+"&id="+encodeURIComponent(p.id),{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"phase",status:p.status==="published"?"draft":"published"})});loadContent()});document.querySelectorAll("[data-lesson-publish]").forEach(b=>b.onclick=async()=>{const d=await api("/api/course-content?courseId="+encodeURIComponent(selected)+"&admin=true");const l=d.lessons.find(x=>x.id===b.dataset.lessonPublish);await api("/api/course-content?courseId="+encodeURIComponent(selected)+"&id="+encodeURIComponent(l.id),{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"lesson",status:l.status==="published"?"draft":"published"})});loadContent()})}
document.addEventListener("DOMContentLoaded",async()=>{try{const s=await api("/api/auth/me");if(s.user.role!=="admin")throw Error("Administrator access required");await loadCourses()}catch(e){location.href="login.html";return}
$("[data-course-select]").onchange=async e=>{selected=e.target.value;await loadContent()};
$("[data-phase-form]").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/api/course-content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"phase",courseId:selected,title:f.get("title"),description:f.get("description"),order:Number(f.get("order")),status:f.get("published")==="on"?"published":"draft"})});e.currentTarget.reset();msg("Phase added.","success");await loadContent()}catch(err){msg(err.message)}};
$("[data-lesson-form]").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/api/course-content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"lesson",courseId:selected,phaseId:f.get("phaseId"),title:f.get("title"),description:f.get("description"),duration:f.get("duration"),videoUrl:f.get("videoUrl"),videoTitle:f.get("videoTitle"),videoDescription:f.get("videoDescription"),videoThumbnail:f.get("videoThumbnail"),videoDuration:f.get("videoDuration"),videoPublished:f.get("videoPublished")==="on",materialUrl:f.get("materialUrl"),materialTitle:f.get("materialTitle"),materialType:f.get("materialType"),materialPublished:f.get("materialPublished")==="on",order:Number(f.get("order")),status:f.get("published")==="on"?"published":"draft"})});e.currentTarget.reset();msg("Lesson added.","success");await loadContent()}catch(err){msg(err.message)}};$("[data-logout]").onclick=async()=>{await api("/api/auth/logout",{method:"POST"});location.href="login.html"}});