import { ObjectId } from "mongodb"; import { getDatabase } from "../_lib/db.js";
const oid=v=>typeof v==="string"&&ObjectId.isValid(v)?new ObjectId(v):null, clean=(v,n=200)=>typeof v==="string"?v.trim().slice(0,n):"";
const json=(r,s,b)=>r.status(s).json(b),token=req=>{const m=(req.headers.cookie||"").match(/(?:^|;\s*)cwu_session=([^;]+)/);return m?decodeURIComponent(m[1]):null};
async function user(req){const t=token(req);if(!t)return null;const db=await getDatabase(),s=await db.collection("sessions").findOne({token:t});return s?db.collection("users").findOne({_id:s.userId}):null}
const map=x=>({...x,id:x._id.toString(),courseId:x.courseId.toString()});
export default async function handler(req,res){try{const u=await user(req);if(!u)return json(res,401,{ok:false,error:"Not authenticated"});if(u.role!=="admin")return json(res,403,{ok:false,error:"Administrator access required"});const db=await getDatabase(),c=db.collection("exams");
if(req.method==="GET"){const rows=await c.find(oid(req.query?.courseId)?{courseId:oid(req.query.courseId)}:{}).sort({createdAt:-1}).toArray();return json(res,200,{ok:true,exams:rows.map(map)})}
if(req.method==="POST"){const b=req.body||{},courseId=oid(b.courseId),title=clean(b.title,160);if(!courseId||!title)return json(res,400,{ok:false,error:"Course and exam title are required"});const doc={courseId,title,description:clean(b.description,1000),questionCount:Math.max(1,Number(b.questionCount)||20),timeLimitMinutes:Math.max(1,Number(b.timeLimitMinutes)||30),passPercent:Math.min(100,Math.max(1,Number(b.passPercent)||70)),maxAttempts:Math.max(1,Number(b.maxAttempts)||1),randomize:b.randomize!==false,status:b.status==="published"?"published":"draft",createdAt:new Date(),updatedAt:new Date()};const r=await c.insertOne(doc);return json(res,201,{ok:true,exam:map({...doc,_id:r.insertedId})})}
if(req.method==="PUT"){const id=oid(req.query?.id);if(!id)return json(res,400,{ok:false,error:"Valid exam id is required"});const b=req.body||{},set={updatedAt:new Date()};if(b.title!==undefined)set.title=clean(b.title,160);if(b.description!==undefined)set.description=clean(b.description,1000);for(const k of ["questionCount","timeLimitMinutes","passPercent","maxAttempts"])if(b[k]!==undefined)set[k]=Math.max(1,Number(b[k])||1);if(set.passPercent!==undefined)set.passPercent=Math.min(100,set.passPercent);if(typeof b.randomize==="boolean")set.randomize=b.randomize;if(b.status==="draft"||b.status==="published")set.status=b.status;const x=await c.findOneAndUpdate({_id:id},{$set:set},{returnDocument:"after"});return x?json(res,200,{ok:true,exam:map(x)}):json(res,404,{ok:false,error:"Exam not found"})}
if(req.method==="DELETE"){const id=oid(req.query?.id);if(!id)return json(res,400,{ok:false,error:"Valid exam id is required"});await c.deleteOne({_id:id});return json(res,200,{ok:true})}return json(res,405,{ok:false,error:"Method not allowed"})}catch(e){console.error(e);return json(res,500,{ok:false,error:"Server configuration or database error"})}}