import { ObjectId } from "mongodb";
import { getDatabase } from "../../api/_lib/db.js";
function json(res,s,b){res.status(s).json(b)}
function token(req){const m=(req.headers.cookie||"").match(/(?:^|;\s*)cwu_session=([^;]+)/);return m?decodeURIComponent(m[1]):null}
async function getUser(req){const t=token(req);if(!t)return null;const db=await getDatabase();const s=await db.collection("sessions").findOne({token:t});if(!s)return null;return db.collection("users").findOne({_id:s.userId})}
const clean=(v,n=4000)=>typeof v==="string"?v.trim().slice(0,n):"";
const oid=v=>typeof v==="string"&&ObjectId.isValid(v)?new ObjectId(v):null;
const map=q=>({id:q._id.toString(),courseId:q.courseId.toString(),question:q.question,options:q.options||[],correctAnswer:q.correctAnswer,topic:q.topic||"",explanation:q.explanation||"",marks:q.marks||1,difficulty:q.difficulty||"medium",type:q.type||"mcq",status:q.status||"draft"});
export default async function handler(req,res){
 try{
  const u=await getUser(req);if(!u)return json(res,401,{ok:false,error:"Not authenticated"});if(u.role!=="admin")return json(res,403,{ok:false,error:"Administrator access required"});
  const db=await getDatabase(),col=db.collection("questions");
  if(req.method==="GET"){const q={},courseId=oid(req.query?.courseId);if(courseId)q.courseId=courseId;if(req.query?.status==="published"||req.query?.status==="draft")q.status=req.query.status;const rows=await col.find(q).sort({createdAt:-1}).limit(500).toArray();return json(res,200,{ok:true,count:rows.length,questions:rows.map(map)})}
  if(req.method==="POST"){const b=req.body||{},courseId=oid(b.courseId);if(!courseId)return json(res,400,{ok:false,error:"Valid courseId is required"});const question=clean(b.question);if(!question)return json(res,400,{ok:false,error:"Question is required"});const type=b.type==="true_false"?"true_false":"mcq";const options=type==="true_false"?["True","False"]:(Array.isArray(b.options)?b.options.map(x=>clean(x,500)).filter(Boolean).slice(0,4):[]);const correct=clean(b.correctAnswer,500);if(options.length<2||!options.includes(correct))return json(res,400,{ok:false,error:"Valid options and correct answer are required"});const doc={courseId,question,options,correctAnswer:correct,topic:clean(b.topic,200),explanation:clean(b.explanation,2000),marks:Math.max(1,Number(b.marks)||1),difficulty:["easy","medium","hard"].includes(b.difficulty)?b.difficulty:"medium",type,status:b.status==="published"?"published":"draft",createdAt:new Date(),updatedAt:new Date()};const r=await col.insertOne(doc);return json(res,201,{ok:true,question:map({...doc,_id:r.insertedId})})}
  if(req.method==="PUT"){const id=oid(req.query?.id);if(!id)return json(res,400,{ok:false,error:"Valid question id is required"});const b=req.body||{},set={updatedAt:new Date()};if(b.status==="draft"||b.status==="published")set.status=b.status;if(b.question!==undefined)set.question=clean(b.question);if(b.topic!==undefined)set.topic=clean(b.topic,200);if(b.explanation!==undefined)set.explanation=clean(b.explanation,2000);if(b.marks!==undefined)set.marks=Math.max(1,Number(b.marks)||1);const r=await col.findOneAndUpdate({_id:id},{$set:set},{returnDocument:"after"});return r?json(res,200,{ok:true,question:map(r)}):json(res,404,{ok:false,error:"Question not found"})}
  if(req.method==="DELETE"){const id=oid(req.query?.id);if(!id)return json(res,400,{ok:false,error:"Valid question id is required"});const r=await col.deleteOne({_id:id});return json(res,200,{ok:true,deleted:r.deletedCount})}
  return json(res,405,{ok:false,error:"Method not allowed"})
 }catch(e){console.error("Question API error:",e);return json(res,500,{ok:false,error:"Server configuration or database error"})}
}