import { ObjectId } from "mongodb";
import { getDatabase } from "../_lib/db.js";
function json(response,status,body){response.status(status).json(body)}
function tokenFromCookie(request){const cookie=request.headers.cookie||"";const match=cookie.match(/(?:^|;\s*)cwu_session=([^;]+)/);return match?decodeURIComponent(match[1]):null}
async function currentUser(request){const token=tokenFromCookie(request);if(!token)return null;const db=await getDatabase();const session=await db.collection("sessions").findOne({token});if(!session)return null;return db.collection("users").findOne({_id:session.userId})}
function courseKey(value){return typeof value==="string"&&ObjectId.isValid(value)?new ObjectId(value):value}
async function totalLessons(db,courseId){return db.collection("lessons").countDocuments({courseId:courseKey(courseId),status:"published"})}
export default async function handler(request,response){
 if(!["GET","PATCH"].includes(request.method))return json(response,405,{ok:false,error:"Method not allowed"});
 try{const user=await currentUser(request);if(!user)return json(response,401,{ok:false,error:"Not authenticated"});const db=await getDatabase(),progress=db.collection("course_progress");
  if(request.method==="PATCH"){const {courseId,lesson}=request.body||{},id=typeof courseId==="string"?courseId.trim():"",lessonNumber=Number(lesson);if(!id||!Number.isInteger(lessonNumber)||lessonNumber<1)return json(response,400,{ok:false,error:"Valid course and lesson are required"});const enrolled=await db.collection("enrollments").findOne({userId:user._id,courseId:id});if(!enrolled)return json(response,403,{ok:false,error:"You must be enrolled in this course"});const total=await totalLessons(db,id);if(!total)return json(response,400,{ok:false,error:"No published lessons are available for this course"});const existing=await progress.findOne({userId:user._id,courseId:id});const previousLesson=Number(existing?.currentLesson||0);if(lessonNumber>previousLesson+1)return json(response,400,{ok:false,error:"Complete lessons in order before skipping ahead"});const completedLesson=Math.max(previousLesson,Math.min(lessonNumber,total));const percent=Math.round((completedLesson/total)*100);await progress.updateOne({userId:user._id,courseId:id},{$set:{currentLesson:completedLesson,progress:percent,totalLessons:total,updatedAt:new Date()},$setOnInsert:{userId:user._id,courseId:id,createdAt:new Date()}},{upsert:true});await db.collection("enrollments").updateOne({userId:user._id,courseId:id},{$set:{progress:percent,updatedAt:new Date()}});return json(response,200,{ok:true,courseId:id,currentLesson:completedLesson,totalLessons:total,progress:percent})}
  const courseId=typeof request.query?.courseId==="string"?request.query.courseId.trim():"",query={userId:user._id};if(courseId)query.courseId=courseId;const items=await progress.find(query).toArray();const mapped=await Promise.all(items.map(async item=>{const total=await totalLessons(db,item.courseId);return {courseId:item.courseId,currentLesson:item.currentLesson||1,progress:item.progress||0,totalLessons:total}}));return json(response,200,{ok:true,progress:mapped});
 }catch(error){console.error("Progress API error:",error);return json(response,500,{ok:false,error:"Server configuration or database error"})}
}