import { ObjectId } from "mongodb";
import { getDatabase } from "../_lib/db.js";
const oid=v=>typeof v==="string"&&ObjectId.isValid(v)?new ObjectId(v):null;
function json(r,s,b){r.status(s).json(b)}
function token(req){const m=(req.headers.cookie||"").match(/(?:^|;\s*)cwu_session=([^;]+)/);return m?decodeURIComponent(m[1]):null}
async function user(req){const t=token(req);if(!t)return null;const db=await getDatabase();const s=await db.collection("sessions").findOne({token:t});return s?db.collection("users").findOne({_id:s.userId}):null}
function publicQuestion(q){return {id:q._id.toString(),question:q.question,options:q.options,marks:q.marks||1,topic:q.topic||"",difficulty:q.difficulty||"medium"}}
export default async function handler(req,res){try{
 const u=await user(req);if(!u)return json(res,401,{ok:false,error:"Not authenticated"});const db=await getDatabase(),quizzes=db.collection("quizzes");
 if(req.method==="GET"){const id=oid(req.query?.id);if(!id)return json(res,400,{ok:false,error:"Valid quiz id is required"});const quiz=await quizzes.findOne({_id:id,status:"published"});if(!quiz)return json(res,404,{ok:false,error:"Quiz not found"});const courseId=quiz.courseId.toString();const enrollment=await db.collection("enrollments").findOne({userId:u._id,courseId});if(!enrollment)return json(res,403,{ok:false,error:"Enroll in this course before taking the quiz"});const progress=await db.collection("course_progress").findOne({userId:u._id,courseId});if(!progress||Number(progress.progress)!==100)return json(res,403,{ok:false,error:"Complete all course lessons before taking the quiz"});const attempts=await db.collection("quiz_attempts").countDocuments({userId:u._id,quizId:id});if(attempts>=quiz.maxAttempts)return json(res,403,{ok:false,error:"Maximum quiz attempts reached"});let questions=await db.collection("questions").find({courseId:quiz.courseId,status:"published"}).toArray();if(!questions.length)return json(res,400,{ok:false,error:"No published questions are available for this quiz"});if(quiz.randomize)questions.sort(()=>Math.random()-0.5);questions=questions.slice(0,Math.min(quiz.questionCount,questions.length));const attempt={userId:u._id,quizId:id,courseId:quiz.courseId,startedAt:new Date(),questionIds:questions.map(q=>q._id),status:"in_progress"};const ar=await db.collection("quiz_attempts").insertOne(attempt);return json(res,200,{ok:true,quiz:{id:id.toString(),title:quiz.title,description:quiz.description,questionCount:questions.length,timeLimitMinutes:quiz.timeLimitMinutes,passPercent:quiz.passPercent,attempt:ar.insertedId.toString(),startedAt:attempt.startedAt},questions:questions.map(publicQuestion)})}
 if(req.method==="POST"){const b=req.body||{},attemptId=oid(b.attemptId);if(!attemptId)return json(res,400,{ok:false,error:"Valid attemptId is required"});const attempt=await db.collection("quiz_attempts").findOne({_id:attemptId,userId:u._id});if(!attempt||attempt.submittedAt||attempt.status==="submitted")return json(res,400,{ok:false,error:"Quiz attempt is invalid or already submitted"});const quiz=await quizzes.findOne({_id:attempt.quizId,status:"published"});if(!quiz)return json(res,404,{ok:false,error:"Quiz not found"});if(Date.now()-new Date(attempt.startedAt).getTime()>quiz.timeLimitMinutes*60000)return json(res,400,{ok:false,error:"Quiz time limit exceeded"});const answers=Array.isArray(b.answers)?b.answers:[];const map=new Map(answers.map(a=>[String(a.questionId),String(a.answer)]));const questions=await db.collection("questions").find({_id:{$in:attempt.questionIds}}).toArray();let score=0,total=0;for(const q of questions){total+=Number(q.marks)||1;if(map.get(q._id.toString())===String(q.correctAnswer))score+=Number(q.marks)||1}const percent=total?Math.round(score/total*100):0;const passed=percent>=quiz.passPercent;const submittedAt=new Date();await db.collection("quiz_attempts").updateOne({_id:attemptId},{$set:{answers,score,total,percent,passed,submittedAt,status:"submitted"}});await db.collection("quiz_results").insertOne({userId:u._id,courseId:attempt.courseId.toString(),quizId:attempt.quizId.toString(),score,total,percent,passed,submittedAt});return json(res,200,{ok:true,score,total,percent,passed,passPercent:quiz.passPercent})}
 return json(res,405,{ok:false,error:"Method not allowed"})}catch(e){console.error("Student quiz API error:",e);return json(res,500,{ok:false,error:"Server configuration or database error"})}}